Searchbar
AlekseyMegliy/ukad-test-react pull request #3
Opened 2023-03-20 15:10 UTC by AlekseyMegliy

2023-03-21 10:31 UTC, ArturNagaycev requested changes
1. When you put some value in searchbar on home page and press Enter - in console you see error - check it.

2. When you put 'aaaaaa' in searchbar - then loading goes constantly. It's better to show message like "With this word there are no items"

3. When you put some word, for example "dog", on Products page, and then you press link "Products" - nothing happens, but must show page-1

2023-03-21 10:31 UTC, a-nahaitsev commented on src/components/header/Header.tsx
> +  function submit(event: any | undefined) {
you can type this variable better than `any`

2023-03-21 10:31 UTC, a-nahaitsev commented on src/components/header/Header.tsx
> +    setSearchValue("");
do you definitely need to clear this variable?

2023-03-21 10:31 UTC, a-nahaitsev commented on src/pages/ProductsPage/Products.tsx
> +  const { data = [] } = useFetchBreedsQuery(pageNum - 1);
Why don't you set `1 && Number(search.get("page"))` as initial state to avoid creating variable `currentPage `?

2023-03-21 10:31 UTC, a-nahaitsev commented on src/pages/ProductsPage/Products.tsx
> +      }, 300);
In my opinion, this is too low a value. We have a lot of requests to server with it

2023-03-21 10:31 UTC, ArturNagaycev commented on src/pages/ProductsPage/Products.tsx
> +        fetch("https://api.thedogapi.com/v1/breeds/search?q=dog")
to me there is something incorrect - why `search?q=dog`?

You make a request to server for all entities with dog in name and then filter, right?
You must make a request with your searchTerm like this - https://api.thedogapi.com/v1/breeds/search?q=${searchTerm} and not filter then

2023-03-21 10:31 UTC, ArturNagaycev commented on src/pages/ProductsPage/Products.tsx
> +      }, 300);
Also, it's better to move this function outside from useEffect

2023-03-21 10:31 UTC, ArturNagaycev commented on src/pages/ProductsPage/Products.tsx
> +      ) : breeds.length ? (
It's better to rewrite it without "if in if"

```
{searchTerm && searchBreeds.length && (....)}
{searchTerm && !searchBreeds.length && (....)}
```

2023-03-22 12:48 UTC, ArturNagaycev commented
1. https://ukad-test-react-6197hez6f-alekseymegliy.vercel.app/products/91 - permanent image loading goes. If there is no image for this dog - load placeholder

2. In my opinion, debounce doesn't work. When I put a search word - there is no delay, request to server goes immediately

2023-03-22 13:27 UTC, ArturNagaycev reviewed
1. https://ukad-test-react-6197hez6f-alekseymegliy.vercel.app/products/91 - permanent image loading goes. If there is no image for this dog - load a placeholder

2. In my opinion, debounce doesn't work. When I put a search word - there is no delay, request to the server goes immediately

3. Searching for an unknown word takes a long time. Check it

2023-03-22 13:27 UTC, ArturNagaycev commented on src/pages/ProductsPage/Products.tsx
> +      {!searchTerm && breeds.length ? (
Not the way i recommended.
You should avoid condition in condition.

2023-03-27 15:10 UTC, IgorNovikov10 requested changes

2023-03-27 15:10 UTC, IgorNovikov10 commented on src/components/header/Header.tsx
> +      <div
better not to render the whole search block on certain page (instead of hiding it through styles)

2023-03-27 15:10 UTC, IgorNovikov10 commented on src/pages/ProductsPage/Products.tsx
> +      const fetching = _.debounce(() => {
move `fetching` function definition outside of the `useEffect`

2023-03-27 15:10 UTC, IgorNovikov10 commented on src/pages/ProductsPage/Products.tsx
> +    search.get("search") || setSearchTerm("");
strange useeffect, what is it used for?

2023-03-27 15:10 UTC, IgorNovikov10 commented on src/pages/ProductsPage/Products.tsx
> +        <></>
better return null instead of empty fragment in such cases

2023-03-28 09:26 UTC, IgorNovikov10 requested changes

2023-03-28 09:26 UTC, IgorNovikov10 commented on package.json
> +    "lodash": "^4.17.21",
you don't need to use the whole `lodash` library if only you use debounce method from it

2023-03-28 09:26 UTC, IgorNovikov10 commented on src/pages/ProductsPage/Products.tsx
> +  const _ = require("lodash");
wrong require

2023-03-28 09:26 UTC, IgorNovikov10 commented on src/pages/ProductsPage/Products.tsx
> +  const _ = require("lodash");
you should import all the dependencies in the top of the file

also, import lodash.debounce and not the  whole lodash library

2023-03-28 11:00 UTC, IgorNovikov10 approved these changes

2023-03-28 11:02 UTC, merged